---
# Hugging Face credentials for gated models. Not required if there are no gated models
hf-username: <CHANGE ME>
hf-token: <CHANGE ME>

# Model artifacts configuration
artifact-configs:

  - artifact-id: all-minilm-l6-v2
    hf-url: https://huggingface.co/sentence-transformers/all-MiniLM-L6-v2
    is-a-gated-model: false

  - artifact-id: bi-encoder
    hf-url: https://huggingface.co/BAAI/bge-small-en-v1.5
    is-a-gated-model: false

  - artifact-id: cross-encoder
    hf-url: https://huggingface.co/cross-encoder/ms-marco-MiniLM-L-6-v2
    is-a-gated-model: false

  - artifact-id: e5-language-classifier
    hf-url: https://huggingface.co/Mike0307/multilingual-e5-language-detection
    is-a-gated-model: false

  - artifact-id: gpt-oss-20b
    hf-url: https://huggingface.co/openai/gpt-oss-20b
    is-a-gated-model: false
    files-to-exclude:
      - metal/
      - original/

  - artifact-id: mbart-translator
    hf-url: https://huggingface.co/facebook/mbart-large-50-many-to-many-mmt
    is-a-gated-model: false

  - artifact-id: gemma-4-31b-it
    hf-url: https://huggingface.co/google/gemma-4-31B-it-qat-w4a16-ct
    is-a-gated-model: false

  - artifact-id: pii-classifier
    hf-url: https://huggingface.co/StanfordAIMI/stanford-deidentifier-base
    is-a-gated-model: false

  - artifact-id: uae-large
    hf-url: https://huggingface.co/WhereIsAI/UAE-Large-V1
    is-a-gated-model: false

  - artifact-id: xlm-roberta-language-classifier
    hf-url: https://huggingface.co/papluca/xlm-roberta-base-language-detection
    is-a-gated-model: false
