apiVersion: ai.splunk.com/v1
kind: AIPlatform
metadata:
  name: splunk-ai-stack
  namespace: ai-platform
spec:
  objectStorage:
    path: s3://my-company-ai-platform--kb
    region: us-west-2

  features:
    - name: weaviate-service
      version: "1.0.0"
      serviceAccountName: saia-service-sa

  storage:
    vectorDB:
      size: 50Gi
      storageClassName: gp3

  splunkConfiguration:
    endpoint: https://splunk-splunk-standalone-standalone-service.ai-platform.svc.cluster.local:8088
    secretRef:
      name: splunk-splunk-standalone-standalone-secret-v1
      namespace: ai-platform

