apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: my-ai-cluster
  region: us-west-2
  version: "1.31"
iam:
  withOIDC: true
addons:
  - name: vpc-cni
  - name: kube-proxy
  - name: coredns
  - name: eks-pod-identity-agent

managedNodeGroups:

  - name: cpu-nodes
    instanceType: m5.xlarge
    desiredCapacity: 4
    minSize: 2
    maxSize: 8
    volumeSize: 500
    volumeType: gp3
    tags:
      Name: my-ai-cluster-cpu
      Environment: prod
      kubernetes.io/cluster/my-ai-cluster: owned
      k8s.io/cluster-autoscaler/enabled: "true"
      k8s.io/cluster-autoscaler/my-ai-cluster: owned
  - name: gpu-nodes
    instanceType: g6e.12xlarge
    desiredCapacity: 2
    minSize: 2
    maxSize: 4
    volumeSize: 1000
    volumeType: gp3
    tags:
      Name: my-ai-cluster-gpu
      Environment: prod
      kubernetes.io/cluster/my-ai-cluster: owned
      k8s.io/cluster-autoscaler/enabled: "true"
      k8s.io/cluster-autoscaler/my-ai-cluster: owned
    taints:
      - key: "nvidia.com/gpu"
        value: "true"
        effect: "NoSchedule"
