cluster:
  useExisting: auto
  name: "my-ai-cluster"
  region: "us-east-2"
  sshUser: "ubuntu"
  sshKeyPath: "/Users/<username>/.ssh/key-pair.pem"        # CHANGE THIS

nodes:
  existingIPs:
    controllers:
      - 3.129.208.144                                      # CHANGE THIS: Your controller server IP
    workers:
      - 18.216.76.189                                      # CHANGE THIS: Your worker server IP

storage:
  storageClass: "local-path"
  vectorDbSize: "50Gi"

kubernetes:
  namespace: "ai-platform"

splunk:
  standaloneName: "splunk-standalone"

images:
  operator:
    image: "docker.io/splunk/splunk-ai-operator:v0.1-weaviate-alpha"
  splunk:
    image: "docker.io/splunk/splunk:10.2"
    operatorImage: "docker.io/splunk/splunk-operator:3.0.0"
  weaviate:
    image: "docker.io/semitechnologies/weaviate:stable-v1.28-007846a"
    proxyImage: "docker-test.repo.splunkdev.net/ml-platform/vector-db/weaviate-service:v1.0.1"

aiPlatform:
  name: "splunk-ai-stack"
  features:
    - name: "weaviate-service"
      version: "1.0.0"
      serviceAccountName: "saia-service-sa"
      env:
        SPLUNK_ISSUERS: "https://splunk-splunk-standalone-standalone-service:8089"

files:
  splunkOperator: "./splunk-operator-cluster.yaml"
  aiPlatform: "./artifacts.yaml"
