L40S:
  - tier: l40s-0-gpu
    gpusPerPod: 0
    env:
      NVIDIA_VISIBLE_DEVICES: void
    resources:
      limits:
        cpu: "16"
        memory: "32Gi"
        ephemeral-storage: "10Gi"
        nvidia.com/gpu: "0"
      requests:
        cpu: "4"
  - tier: l40s-1-gpu
    gpusPerPod: 1
    resources:
      requests:
        cpu: "4"
      limits:
        cpu: "16"
        memory: "64Gi"
        ephemeral-storage: "200Gi"
        nvidia.com/gpu: "1"
  - tier: l40s-2-gpu
    gpusPerPod: 2
    resources:
      requests:
        cpu: "1"
      limits:
        cpu: "2"
        memory: "48Gi"
        ephemeral-storage: "100Gi"
        nvidia.com/gpu: "2"
  - tier: l40s-4-gpu
    gpusPerPod: 4
    resources:
      requests:
        cpu: "1"
      limits:
        cpu: "8"
        memory: "96Gi"
        ephemeral-storage: "200Gi"
        nvidia.com/gpu: "4"
H100:
  - tier: h100-0-gpu
    gpusPerPod: 0
    env:
      NVIDIA_VISIBLE_DEVICES: void
    resources:
      limits:
        cpu: "16"
        memory: "32Gi"
        ephemeral-storage: "10Gi"
        nvidia.com/gpu: "0"
      requests:
        cpu: "4"
  - tier: h100-1-gpu
    gpusPerPod: 1
    # No NVIDIA_VISIBLE_DEVICES here - GPUs must be visible for vLLM
    resources:
      requests:
        cpu: "4"
      limits:
        cpu: "16"
        memory: "48Gi"
        ephemeral-storage: "100Gi"
        nvidia.com/gpu: "1"
H100_NVL:
  - tier: h100-nvl-0-gpu
    gpusPerPod: 0
    resources:
      limits:
        cpu: "16"
        memory: "32Gi"
        ephemeral-storage: "10Gi"
        nvidia.com/gpu: "0"
      requests:
        cpu: "4"
  - tier: h100-nvl-1-gpu
    gpusPerPod: 1
    resources:
      requests:
        cpu: "4"
      limits:
        cpu: "16"
        memory: "48Gi"
        ephemeral-storage: "100Gi"
        nvidia.com/gpu: "1"
RTX_PRO_6000_BLACKWELL:
  - tier: rtx-pro-6000-blackwell-0-gpu
    gpusPerPod: 0
    resources:
      limits:
        cpu: "16"
        memory: "24Gi"
        ephemeral-storage: "50Gi"
        nvidia.com/gpu: "0"
      requests:
        cpu: "4"
  - tier: rtx-pro-6000-blackwell-1-gpu
    gpusPerPod: 1
    resources:
      requests:
        cpu: "4"
      limits:
        cpu: "16"
        memory: "48Gi"
        ephemeral-storage: "200Gi"
        nvidia.com/gpu: "1"
  - tier: rtx-pro-6000-blackwell-2-gpu
    gpusPerPod: 2
    resources:
      requests:
        cpu: "4"
      limits:
        cpu: "8"
        memory: "96Gi"
        ephemeral-storage: "400Gi"
        nvidia.com/gpu: "2"