applicationScale:
  AllMinilmL6V2: 1
  BiEncoder: 1
  CrossEncoder: 1
  E5LanguageClassifier: 1
  Entrypoint: 1
  FmTimeseries: 1
  Gemma431bIt: 1
  GptOss20b: 1
  MbartTranslator: 1
  PromptInjectionClassifier: 1
  PromptInjectionCrossEncoder: 1
  PromptInjectionTfidf: 1
  UaeLarge: 1
  XlmRobertaLanguageClassifier: 1
