name: Release Workflow
on:
  push:
    branches:
      - main
      - helm_chart_releaser

permissions:
  actions: read
  contents: write

jobs:
  release-charts:
    uses: ./.github/workflows/release-helm-charts.yml
